name: Build v2

on:
  push:
    branches:
      - 'master'

jobs:
  build:
      if: github.event.pull_request.merged == 'true'
      runs-on: "ubuntu-latest"
      steps:
          - uses: actions/checkout@v2
          - name: Install node
            uses: actions/setup-node@v1
            with:
                node-version: 14.x

          - name: Run build
            run: |
              npm install
              npm run build

          - name: Copy files to root folder
            run: |
              cp -R ./dist/* ./

          - name: Commit files
            run: |
              git config --global user.name ${{ github.actor }}
              git config --global user.email newkipsoftware@gmail.com
              git add .
              git commit -m 'Build'

          - name: Push changes
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              force: true
