name: Generate data

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
      - cron:  '*/15 * * * *'

jobs:
  generate:
    runs-on: "ubuntu-latest"     

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
            node-version: 14.x

      - name: Run job
        run: |
          cd job
          npm install
          node index

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./data.json
          git commit -m 'Data update'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true


